<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html>

<head>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1"/>
<meta name="description" content="description"/>
<meta name="keywords" content="keywords"/> 
<meta name="author" content="author"/> 
<link rel="stylesheet" type="text/css" href="../themes/transparentia/default.css" media="screen"/>

<title> <?php echo $pageconf->title; ?> </title>
<?php jscms_include_common_js(); ?>
</head>

<body>
<div class="container">
	<div class="main">
		<div class="header"><div class="title"><h1 id="theheader"><?php echo $pageconf->heading; ?></h1></div> </div>
		<div id="thecontent" class="content"> </div>
		<div id="thesidebar" class="sidenav"> </div>
		<div class="clearer"><span></span></div>
	</div>
	<div id="thefooter" class="footer"> </div>
	<div class="footermandatory">&copy; 2006 <a href="../page1">Back to greenery</a>. Valid <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> &amp; <a href="http://validator.w3.org/check?uri=referer">XHTML</a>. Template design by <a href="http://templates.arcsin.se">Arcsin</a>
	</div>
</div>
<?php jscms_include_mm(); ?>
</body>
</html>
