<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<!-- *****************************
** green lush css based layout  **
** ---------------------------- **
** author: Yamazaki             **
** this layout is free for      **
** download, however you can't  **
** redistribute it and put the  **
** zip / rar file in your web   **
** without any permissions from **
** the author. thank you        **
** ---------------------------- **
** have fun with the layout     **
****************************** -->


<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <title> <?php echo $pageconf->title; ?></title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="green lush is a greeny layout with a valid XHTML 1.1 strict and CSS 2 specification" />
    <meta name="keywords" content="layout, css layout, xhtml layout, css, xhtml, webstandards, free, free layout, free div layout" />
    <meta name="author" content="Yamazaki" />

    <link rel="stylesheet" type="text/css" href="../themes/greenlush/css.css" media="screen" />

    <?php jscms_include_common_js(); ?>
</head>

<body>
<div id="container">

	<div id="header"><div class="headtitle">
	<?php echo $pageconf->heading; ?>
	</div></div>

	<div id="menu">
		<ul>
			<li><a href="#" title="">HOME</a></li>
			<li><a href="#" title="">ABOUT ME</a></li>
			<li><a href="#" title="">MY WORKS</a></li>
			<li><a href="#" title="">SERVICES</a></li>
			<li><a href="#" title="">DOWNLOAD</a></li>
			<li><a href="#" title="">CONTACT ME</a></li>
			<li><a href="#" title="">QUICK MESSAGE</a></li>
			<li><a href="../tr" title="">OYSTER</a></li>
		</ul>
	</div>
	
	<div id="roundedheader">&nbsp;</div>
	
	<div id="content">
            <div id='leftcontainer'>
                <div id='maincontent'>	
                </div>
            </div>
		
	    <div id="sidebar"> 
	    </div>
		
	    <div style="clear: both;"></div>
		
	</div>
	<div id="roundedfooter">&nbsp;</div>
	
	<div id="footer"></div>
</div>
<?php jscms_include_mm(); ?>
</body>
</html>
